module Alphabet

// pixels are 8 wide, 10 tall
// with one pixel space border, is 10x12

let letters = 
    [|
        [|  ".........."
            "..XXXXXX.."
            ".XXXXXXXX."
            ".XX....XX."
            ".XX....XX."
            ".XXXXXXXX."
            ".XXXXXXXX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."    
            ".........."
        |]
        [|  ".........."
            ".XXXXXXX.."
            ".XXXXXXXX."
            ".XX....XX."
            ".XX....XX."
            ".XXXXXXX.."
            ".XXXXXXX.."
            ".XX....XX."
            ".XX....XX."
            ".XXXXXXXX."
            ".XXXXXXX.."    
            ".........."
        |]
        [|  ".........."
            "..XXXXXX.."
            ".XXXXXXXX."
            ".XX....XX."
            ".XX......."
            ".XX......."
            ".XX......."
            ".XX......."
            ".XX....XX."
            ".XXXXXXXX."
            "..XXXXXX.."    
            ".........."
        |]
        [|  ".........."
            ".XXXXXX..."
            ".XXXXXXX.."
            ".XX...XXX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX...XXX."
            ".XXXXXXX.."
            ".XXXXXX..."    
            ".........."
        |]
        [|  ".........."
            ".XXXXXXXX."
            ".XXXXXXXX."
            ".XX......."
            ".XX......."
            ".XXXXXX..."
            ".XXXXXX..."
            ".XX......."
            ".XX......."
            ".XXXXXXXX."
            ".XXXXXXXX."    
            ".........."
        |]
        [|  ".........."
            ".XXXXXXXX."
            ".XXXXXXXX."
            ".XX......."
            ".XX......."
            ".XXXXXX..."
            ".XXXXXX..."
            ".XX......."
            ".XX......."
            ".XX......."
            ".XX......."    
            ".........."
        |]
        [|  ".........."
            "..XXXXXX.."
            ".XXXXXXXX."
            ".XX......."
            ".XX......."
            ".XX..XXXX."
            ".XX..XXXX."
            ".XX....XX."
            ".XX....XX."
            ".XXXXXXXX."
            "..XXXXXX.."    
            ".........."
        |]
        [|  ".........."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XXXXXXXX."
            ".XXXXXXXX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."    
            ".........."
        |]
        [|  ".........."
            ".XXXXXXXX."
            ".XXXXXXXX."
            "....XX...."
            "....XX...."
            "....XX...."
            "....XX...."
            "....XX...."
            "....XX...."
            ".XXXXXXXX."
            ".XXXXXXXX."    
            ".........."
        |]
        [|  ".........."
            ".......XX."
            ".......XX."
            ".......XX."
            ".......XX."
            ".......XX."
            ".......XX."
            ".XX....XX."
            ".XX....XX."
            ".XXXXXXXX."
            "..XXXXXX.."    
            ".........."
        |]
        [|  ".........."
            ".XX....XX."
            ".XX...XX.."
            ".XX..XX..."
            ".XX.XX...."
            ".XXXX....."
            ".XXXX....."
            ".XX.XX...."
            ".XX..XX..."
            ".XX...XX.."
            ".XX....XX."    
            ".........."
        |]
        [|  ".........."
            ".XX......."
            ".XX......."
            ".XX......."
            ".XX......."
            ".XX......."
            ".XX......."
            ".XX......."
            ".XX......."
            ".XXXXXXXX."
            ".XXXXXXXX."    
            ".........."
        |]
        [|  ".........."
            ".XX....XX."
            ".XX....XX."
            ".XXX..XXX."
            ".XXXXXXXX."
            ".XX.XX.XX."
            ".XX.XX.XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."    
            ".........."
        |]
        [|  ".........."
            ".XX....XX."
            ".XX....XX."
            ".XXX...XX."
            ".XXXX..XX."
            ".XXXXX.XX."
            ".XX.XXXXX."
            ".XX..XXXX."
            ".XX...XXX."
            ".XX....XX."
            ".XX....XX."    
            ".........."
        |]
        [|  ".........."
            "..XXXXXX.."
            ".XXXXXXXX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XXXXXXXX."
            "..XXXXXX.."    
            ".........."
        |]
        [|  ".........."
            ".XXXXXXX.."
            ".XXXXXXXX."
            ".XX....XX."
            ".XX....XX."
            ".XXXXXXXX."
            ".XXXXXXX.."
            ".XX......."
            ".XX......."
            ".XX......."
            ".XX......."    
            ".........."
        |]
        [|  ".........."
            "..XXXXXX.."
            ".XXXXXXXX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX.XX.XX."
            ".XX..XXXX."
            ".XX...XXX."
            ".XXXXXXXX."
            "..XXXXXX.."    
            ".........."
        |]
        [|  ".........."
            ".XXXXXXX.."
            ".XXXXXXXX."
            ".XX....XX."
            ".XX....XX."
            ".XXXXXXXX."
            ".XXXXXXX.."
            ".XX...XX.."
            ".XX...XXX."
            ".XX....XX."
            ".XX....XX."    
            ".........."
        |]
        [|  ".........."
            "..XXXXXX.."
            ".XXXXXXXX."
            ".XX....XX."
            ".XX......."
            ".XXXXXXX.."
            "..XXXXXXX."
            ".......XX."
            ".XX....XX."
            ".XXXXXXXX."
            "..XXXXXX.."    
            ".........."
        |]
        [|  ".........."
            ".XXXXXXXX."
            ".XXXXXXXX."
            "....XX...."
            "....XX...."
            "....XX...."
            "....XX...."
            "....XX...."
            "....XX...."
            "....XX...."
            "....XX...."    
            ".........."
        |]
        [|  ".........."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XXXXXXXX."
            "..XXXXXX.."    
            ".........."
        |]
        [|  ".........."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            "..XX..XX.."
            "..XX..XX.."
            "..XX..XX.."
            "..XX..XX.."
            "...XXXX..."
            "....XX...."    
            ".........."
        |]
        [|  ".........."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XX.XX.XX."
            ".XX.XX.XX."
            ".XX.XX.XX."
            ".XXXXXXXX."
            ".XXXXXXXX."
            "..XX..XX.."    
            ".........."
        |]
        [|  ".........."
            ".XX....XX."
            ".XXX..XXX."
            "..XX..XX.."
            "...XXXX..."
            "....XX...."
            "....XX...."
            "...XXXX..."
            "..XX..XX.."
            ".XXX..XXX."
            ".XX....XX."    
            ".........."
        |]
        [|  ".........."
            ".XX....XX."
            ".XX....XX."
            ".XX....XX."
            ".XXX..XXX."
            "..XXXXXX.."
            "...XXXX..."
            "....XX...."
            "....XX...."
            "....XX...."
            "....XX...."
            ".........."
        |]
        [|  ".........."
            ".XXXXXXXX."
            ".XXXXXXXX."
            "......XXX."
            ".....XXX.."
            "....XXX..."
            "...XXX...."
            "..XXX....."
            ".XXX......"
            ".XXXXXXXX."
            ".XXXXXXXX."    
            ".........."
        |]
    |]

let underscore = 
        [|  ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".XXXXXXXX."
            ".XXXXXXXX."
            ".........."
        |]

let space = 
        [|  ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".........."
            ".........."
        |]
